name: Main Tag CI

on:
  push:
    tags:        
      - '*'   
    paths:
      - '.github/workflows/main_ci.yml'
      - 'cmake/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg-configuration.json'
      - 'vcpkg.json'
  pull_request:
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: 93895b28ea7bc8cda10f156c5d336f3fc070f8b1

jobs:
  build-vcpkg:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          submodules: recursive

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: 'vs2022-windows'
          buildPreset: 'vs2022-windows'
          buildPresetAdditionalArgs: "['--config Release']"

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: execute py script 
        run: python ${{ github.workspace }}/main/scripts/archive_artifacts.py --name SkyrimCharacterSheet --dll main/build/Release/SkyrimCharacterSheet.dll --pdb main/build/Release/SkyrimCharacterSheet.pdb

      - uses: actions/upload-artifact@v4
        with:
          name: SkyrimCharacterSheet
          path: ${{ github.workspace }}/main/scripts/artifacts/SkyrimCharacterSheet.zip
